server:
  port: 8080
  error:
    include-message: always

spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: gabrielhs20
    password: password
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  # Flyway configuration
  flyway:
    enabled: true
    # locations: classpath:db/migration # If necessary.
    baseline-on-migrate: true
    baseline-version: 1







  
  # Application Configuration
  main:
    web-application-type: servlet

